" vimrc

"
set nocompatible
filetype on
filetype off
syn on

" EXTENSIONS {{{

" Utils {{{
" source ~/.vim/functions/util.vim
" }}}

" _. Buffer Handling {{{
source ~/.vim/functions/buffer_handling.vim
" }}}

" _. Tab {{{
source ~/.vim/functions/insert_tab_wrapper.vim
" }}}

" }}}

" Load external configuration before anything else {{{
if filereadable(expand("~/.vim/before.vimrc"))
  source ~/.vim/before.vimrc
endif
" }}}

let mapleader = ","
let maplocalleader = "\\"

" VUNDLE {{{
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
" }}}

" Install user-supplied Bundles {{{
for fpath in split(globpath('~/.vim/settings', '*.vim'), '\n')
  exec ':so ' . fpath
endfor
" }}}

" Load addidional configuration (ie to overwrite shorcuts) {{{
if filereadable(expand("~/.vim/after.vimrc"))
  source ~/.vim/after.vimrc
endif

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
set background=dark
colorscheme solarized
" }}}
