#! /bin/bash
XAUTHPORT=$(echo $DISPLAY | cut -d'.' -f1 |  cut -d':' -f2)
xauth extract /tmp/x11-auth-file ":$XAUTHPORT"
chmod 660 /tmp/x11-auth-file
chgrp amdgpu /tmp/x11-auth-file

cat > /tmp/enable-amd-compute <<EOF
export COMPUTE=$DISPLAY
unset DISPLAY
export XAUTHORITY=/tmp/x11-auth-file
EOF
